import "@mantine/core/styles.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import "../styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { theme } from "@/config/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<ColorSchemeScript />
				<link rel="shortcut icon" href="/favicon.svg" />
			</head>
			<body className={inter.className}>
				<MantineProvider theme={theme}>{children}</MantineProvider>
			</body>
		</html>
	);
}
