name: CI
on: [push]

jobs:
  build:
    name: Lint and Typecheck
    env:
      SKIP_ENV_VALIDATION: 1

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18.x, 20.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install deps (with cache)
        run: pnpm install

      - name: Next.js cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ matrix.os }}-${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}-nextjs

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck
